### ISSUE TITLE
Adding Clinvar to genome nexus

### ISSUE THREAD

**Issue by jjgao** [knowledgesystems/signal#104]
[17:g.41276045_41276046del](https://www.signaldb.org/variant/17:g.41276045_41276046del) is the most prevalent pathogenic germline mutation, but the links to ClinVar and dbSNP is missing. It is linked to [gnomAD](https://gnomad.broadinstitute.org/variant/17-41276044-ACT-A), which contains link to dbSNP and ClinVar. 

Similarly: https://www.signaldb.org/variant/17:g.41209079_41209080insG

Solution:
Adding clinvar to genome nexus.

- [x] Import clinvar VCF to genome nexus
- [x] Update genome nexus to query clinvar
- [ ] Find a way to automatically update clinvar data (github action or some other ways) (Create separate issue)

**Comment by leexgh** [comment]
@jjgao We get ClinVar from [MyVariantInfo](https://myvariant.info/v1/variant/chr17:g.41276045_41276046del), but they don't have ClinVar for this particular variant. Actually I already asked them about the same variant before: https://github.com/biothings/myvariant.info/issues/106. Haven't heard back from them yet.

**Comment by inodb** [comment]
There might also be new updates to Ensembl's clinvar data so we might be able to use that over myvariant.info

**Comment by leexgh** [comment]
https://grch37.ensembl.org/info/genome/variation/species/sources_documentation.html
GRCH37 ClinVar version: 12/2019

**Comment by leexgh** [comment]
1. XML:
- Pros: Full data
- Cons: Too big to parse(15GB); Genomic coordinate is not unique; Hard to find a tool to do streaming parsing.
2. VCF:
- Pros: Easy to parse
- Cons: Missing clinical significance data.
3. API
- Pros: Full data
- Cons: Have access control(3 queries per second); Still need a tool to parse XML.

**Comment by leexgh** [comment]
We decide to use VCF. We should be consistant with clinVar interpretation and have linkout to their website, therefor using VCF is better.
