### ISSUE TITLE
Formatting issue with the cancer type decomposition table

### ISSUE THREAD

**Issue by onursumer** [knowledgesystems/signal#107]
- Go to https://deploy-preview-106--signaldb.netlify.app/gene/NF1?mutationStatus=Germline%20-%20Benign%2FVUS
- Expand the cancer type table for the 4th mutation from top (cancer type: `Cervical Cancer, Embryonal Tumor, ...`)

You will see that total prevalence value is not formatted properly. This is most likely affecting the `Signal` column in cBioPortal mutation table as well.

![total_prevalence](https://user-images.githubusercontent.com/3604198/108232221-89c90480-7110-11eb-8271-d2bc2228c7e3.png)

**Comment by leexgh** [comment]
oops I can fix this
