### ISSUE TITLE
 A prevalence heatmap of pathogenic germline variants (genes vs tumor types)

### ISSUE THREAD

**Issue by inodb** [knowledgesystems/signal#53]
on the landscape page

**Comment by onursumer** [comment]
Looks like victory doesn't have an out-of-the-box heatmap component: https://github.com/FormidableLabs/victory/issues/262

We may want to give plotly a try.

**Comment by onursumer** [comment]
Additional heat map features:

- [ ] Heatmap by penetrance level. 
- [ ] Clicking on the circle takes us to a variants list page.
- [ ] Rotate axes. Genes on Y-axis and Cancer Types on X-axis. 
- [ ] Show N (number of samples) with cancer types. And, abbreviate them.
- [ ] Remove out “Unknown/Other/CUP”.
- [ ] Show actual Ns (number of samples) in the pop-up balloon.
- [ ] Options to interactively add/remove genes and cancer types.
