### ISSUE TITLE
Add search box to home page

### ISSUE THREAD

**Issue by leexgh** [knowledgesystems/signal#65]
The search function will support Gene, Variant and Region eventually. 
First step:
- [x] support Variant
- [x] validate variant format
- [x] update examples with existing signal mutations

#### Future work:
- [x] recognize input as Variant / Gene / Region
- [x] update search example to include Gene and Region

**Gene**
- [x] support Gene

**Region**
- [x] support Region

**Comment by inodb** [comment]
@leexgh let's work on gene this sprint

**Comment by onursumer** [comment]
We have decided to have a search functionality very similar to [OncoKB](https://www.oncokb.org/) with a search endpoint on genome nexus backend (see genome-nexus/genome-nexus#456).
