### ISSUE TITLE
Import new signal data to database

### ISSUE THREAD

**Issue by leexgh** [knowledgesystems/signal#69]
Mockup: https://docs.google.com/presentation/d/1G3sQQ7LGRuMl8U0mruNb6lgqxtUKiu_AN3w3vzMGji4/edit#slide=id.p

![image](https://user-images.githubusercontent.com/16869603/98198371-ccb2f380-1ef6-11eb-8de0-fd72412d6a52.png)
![image](https://user-images.githubusercontent.com/16869603/98198388-d63c5b80-1ef6-11eb-91a7-68a625aa6083.png)

Backend:
- [x] Import data to genome nexus database. For now just merge everything into the SignalMutation model. (fixed by genome-nexus/genome-nexus-importer#37)
- [x] Build signal API to expose fields we need in the frontend

**Comment by dippindots** [comment]
@inodb @onursumer @leexgh , just wanted to provide some information about `mutational signatures`, I know currently CVR is using this category mapping, and the reference can be found in this paper: https://pubmed.ncbi.nlm.nih.gov/28481359/

Cat | Sign
-- | --
AGEING | Signature.1
APOBEC | Signature.13
APOBEC | Signature.2
BRCA | Signature.3
MMR | Signature.15
MMR | Signature.20
MMR | Signature.26
MMR | Signature.6
OTHER | Signature.12
OTHER | Signature.16
OTHER | Signature.17
OTHER | Signature.18
OTHER | Signature.19
OTHER | Signature.21
OTHER | Signature.22
OTHER | Signature.23
OTHER | Signature.24
OTHER | Signature.25
OTHER | Signature.27
OTHER | Signature.28
OTHER | Signature.30
OTHER | Signature.5
OTHER | Signature.8
OTHER | Signature.9
POLE | Signature.10
POLE/MMR | Signature.14
SMOKING | Signature.4
TMZ | Signature.11
TOBACCO | Signature.29
UV | Signature.7

**Comment by leexgh** [comment]
@onursumer @inodb @dippindots Thanks!
There are two columns I'm not sure how to map - `Sig.HRD` and `Sig.OxoG`.

And `Sig.APOBEC` and `Sig.MMR` are represented by multiple numbers


Sig.27 | 27
-- | --
Sig.28 | 28
Sig.29 | 29
Sig.30 | 30
Sig.5 | 5
Sig.8 | 8
Sig.9 | 9
Sig.Aging | 1
Sig.APOBEC | 13 / 2
Sig.HRD | ?
Sig.MMR | 15 / 20 / 26 / 6
Sig.OxoG | ?
Sig.POLE | 10
Sig.Smoking | 4
Sig.TMZ | 11
Sig.UV | 7

**Comment by leexgh** [comment]
Also we don't have sig 3, 18, 21

**Comment by dippindots** [comment]
This sheet recorded the category from [COSMIC](https://cancer.sanger.ac.uk/cosmic/signatures_v2.tt) and CVR. The second column of this sheet https://docs.google.com/spreadsheets/d/14IwFf8WtGfS_6XUdMtbXU2VWKcU3LxjPj1mAsrlsitw/edit?usp=sharing shows that `HRD` could be `sig3`. Not sure what's the `OxoG` could be.
